
# ========= Border =========
file_panel_border = '#ccc9b3'
sidebar_border = '#ccc9b3'
footer_border = '#ccc9b3'

# ========= Border Active =========
file_panel_border_active = '#cdb698'
sidebar_border_active = '#cdb698'
footer_border_active = '#cdb698'
modal_border_active = '#cdb698'

# ========= Background (bg) =========
full_screen_bg = '#3b3b2b'
file_panel_bg = '#3b3b2b'
sidebar_bg = '#3b3b2b'
footer_bg = '#3b3b2b'
modal_bg = '#3b3b2b'

# ========= Foreground (fg) =========
full_screen_fg = '#ccb3b3'
file_panel_fg = '#ccb3b3'
sidebar_fg = '#ccb3b3'
footer_fg = '#ccb3b3'
modal_fg = '#ccb3b3'

# ========= Special Color =========
cursor = '#ccb3b3'
correct = '#9fc6a3'
error = '#cdb398'
hint = '#b4cd98'
cancel = '#cdb398'
gradient_color = ['#3b3b2b', "#818165"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#3b3b2b'
file_panel_top_path = '#818165'
file_panel_item_selected_fg = '#818165'
file_panel_item_selected_bg = '#3b3b2b'

# ========= Sidebar Special Items =========
sidebar_title = '#ccb3b3'
sidebar_item_selected_fg = '#818165'
sidebar_item_selected_bg = '#3b3b2b'
sidebar_divider = '#ccc9b3'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#cdb398'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#9fc6a3'
